### ISSUE TITLE
Ability to open AWS console from the app

### ISSUE THREAD

**Issue by ashishpandey001** [loladotdev/lola#22] opened 2022-07-08 07:31 UTC
### Describe the solution you'd like?

A top-level shortcut mapped to a key (probably `c`) to open the AWS console home page directly.

While I can open the console when I'm browsing a resource, it'll open the console page to that specific resource, so having a top-level shortcut would be great.

Maybe we could have a /console <service-name> to be able to open the console page for that service directly. So, /console mediaconvert would open the AWS Elemental MediaConvert home page.

**Comment by aeby** [comment] 2022-07-10 16:42
Thanks, close as duplicate of #19

**Closed as completed** 2022-07-10 17:13 UTC
